### ISSUE TITLE
delay

### ISSUE THREAD

**Issue by ghost** [lopspower/RxAnimation#5]
All the functions have duration: Long, interpolator: TimeInterpolator, startDelay: Long and reverse: Boolean properties.

Not resize, i need a startDelay please ;)

**Comment by lopspower** [comment]
I can't add this parameter here because this function is a combination of two functions. The easiest way is to add a `delay` on your side by managing your flow with the right scheduler like this:

```kotlin
btn.clicks()
    .delay(2, TimeUnit.SECONDS, AndroidSchedulers.mainThread())
    .switchMapCompletable {
        view.resize(0, 0, ANIMATION_DURATION, reverse = true)
    }.subscribe().addTo(composite)
```

**Comment by ghost** [comment]
OK great, thanks for your answer
