### ISSUE TITLE
Cannot get this to work

### ISSUE THREAD

**Issue by monsterbrain** [lopspower/RxAnimation#8]
Tried to implement this in a project . doesn't seems to be working for me. So I made a sample project and add this code ... Can you guide me what i did wrong ?

findViewById<Button>(R.id.button).apply {
            alpha(1f).andThen(this.translation(10f,20f))
        }

        By the way I am using Constraint Layout ..

**Comment by lopspower** [comment]
You have to subscribe the Rx flow to trigger the animation. You have to look at the basics of Rx to understand this before using the library.
